version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DB_HOST}:${DB_PORT}:5432"

  redis:
    image: redis:latest
    restart: always
    env_file:
      - .env
    environment:
      REDIS_PASSWORD: $REDIS_PASSWORD
      REDIS_PORT: $REDIS_PORT
    volumes:
      - redis-data:/root/redis
      - redis-conf:/usr/local/etc/redis/redis.conf
    ports:
      - "${REDIS_HOST}:${REDIS_PORT}:6379"

volumes:
  db-data:
  redis-data:
  redis-conf:
