# Generated by Django 5.0.1 on 2024-02-27 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                ("name", models.CharField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                "db_table": "colors",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "code",
                    models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
                ),
                ("number_of_pawns", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "rooms",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(default="Anonymous", max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "players",
            },
        ),
        migrations.CreateModel(
            name="Pawn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_lead", models.BooleanField(default=False)),
                ("score", models.PositiveSmallIntegerField(default=0)),
                (
                    "color",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="game.color"),
                ),
                (
                    "player",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pawn",
                        to="game.player",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pawns",
                        to="game.room",
                    ),
                ),
            ],
            options={
                "db_table": "pawns",
            },
        ),
    ]
