# Generated by Django 5.0.1 on 2024-02-28 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
            options={
                "db_table": "cards",
            },
        ),
        migrations.CreateModel(
            name="RoomCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("association", models.CharField(max_length=200, null=True)),
                (
                    "pawn",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_card",
                        to="game.pawn",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card",
                        to="game.room",
                    ),
                ),
            ],
            options={
                "db_table": "room_cards",
            },
        ),
        migrations.CreateModel(
            name="PawnVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "pawn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote",
                        to="game.pawn",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pawn_vote",
                        to="game.roomcard",
                    ),
                ),
            ],
            options={
                "db_table": "pawn_votes",
            },
        ),
        migrations.AddConstraint(
            model_name="roomcard",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("pawn",),
                name="unique_active_card_pawn",
            ),
        ),
    ]
