# Generated by Django 5.0.1 on 2024-02-28 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_card_roomcard_pawnvote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomcard",
            name="card",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room",
                to="game.card",
            ),
            preserve_default=False,
        ),
    ]
