# Generated by Django 5.0.3 on 2024-03-05 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_roomcard_card"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pawnvote",
            name="card",
        ),
        migrations.RemoveField(
            model_name="room",
            name="number_of_pawns",
        ),
        migrations.AddField(
            model_name="pawnvote",
            name="room_card",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pawn_votes",
                to="game.roomcard",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="roomcard",
            name="pawn",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_cards",
                to="game.pawn",
            ),
        ),
        migrations.AlterField(
            model_name="roomcard",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="cards", to="game.room"
            ),
        ),
    ]
